name: exercise 02
on:
  workflow_dispatch:
jobs:
  matrix-exercise:
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [20, 21, 22]
        exclude:
          - os: ubuntu-latest
            node: 20
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - if: matrix.os == 'ubuntu-latest' && matrix.node == 20
        run: exit 1
