name: exercise 02
on:
  workflow_dispatch:
jobs:
  matrix-exercise:
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [20, 21, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
