name: events
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
  # push:
  #   branches-ignore:
  #     - feature/**
jobs:
  log-date:
    runs-on: ubuntu-latest
    steps:
      - run: date
