name: expressions
on: workflow_dispatch
jobs:
  testing-expressions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18, 20, 22]
        # name:
        #   - pepe
        #   - lucia
        #   - marcos
        # color: [blue, pink, yellow]
    steps:
      - run: echo ${{ github.actor }}
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      # - run: echo ${{ matrix.name }} ${{ matrix.color }}
